version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: python manage.py runserver --nostatic 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8008:8000"
        depends_on:
            - db
